basic.showIcon(IconNames.Silly)
basic.forever(function () {
    basic.showNumber(1)
    basic.pause(100)
    basic.showNumber(2)
    basic.pause(100)
    basic.showNumber(3)
    basic.pause(100)
    basic.showNumber(4)
    basic.pause(100)
    basic.showNumber(5)
})
